# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - shorts.md

footer: 'follow <a href="https://www.instagram.com/iaac_macad/">IAAC MaCAD</a> on Instagram'

style: dark # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
